from tkinter import*
sf=Tk()
sf.title('STUDENT FORM')
Label(sf,text='Student regid:').grid(row=0)
Label(sf,text='Student name:').grid(row=1)
Label(sf,text='Father name:').grid(row=2)
Label(sf,text='Group:').grid(row=3)
Label(sf,text='Phone number:').grid(row=4)
Label(sf,text='Email id:').grid(row=5)
Label(sf,text='Address:').grid(row=6)
Entry(sf).grid(row=0,column=1)
Entry(sf).grid(row=1,column=1)
Entry(sf).grid(row=2,column=1)
Entry(sf).grid(row=3,column=1)
Entry(sf).grid(row=4,column=1)
Entry(sf).grid(row=5,column=1)
Entry(sf).grid(row=6,column=1)
Button(sf,text='Submit').grid(row=7)
Button(sf,text='Cancle').grid(row=7,column=1)
mainloop()
